version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)-8s - %(message)s'
    datefmt: "%d/%m/%Y %H:%M:%S"
handlers:
  file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: simple
    filename: logs/my_application.log
    when: midnight
    encoding: utf8
loggers:
  simpleLogger:
    handlers: [file]
    propagate: no
root:
  level: INFO
  handlers: [file]